spring:
  application:
    name: ServicesEnrollment
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
